CUDA_LAUNCH_BLOCKING=1 torchrun --nproc_per_node=8 --master_port=1234 finetune.py \
    --task_type sequential \
    --cache_dir cache_dir/ \
    --output_dir ./output \
    --batch_size 512 \
    --micro_batch_size 64 \
    --num_epochs 3 \
    --learning_rate 0.001 \
    --cutoff_len 4096 \
    --lora_r 16 \
    --lora_alpha 16 \
    --lora_dropout 0.05 \
    --lora_target_modules '[gate_proj,down_proj,up_proj]' \
    --train_on_inputs False \
    --add_eos_token False \
    --group_by_length False \
    --prompt_template_name alpaca \
    --warmup_steps 100 \
    --lr_scheduler cosine \
    --llama_decoder_nums 8